services:
  aiohttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/aio-libs/aiohttp
        APP_VERSION: b7ffe616d90d4114f2b78c78f6cf21af4fd106d2
      context: ./images/aiohttp
    x-props:
      role: origin
  apache_httpd:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 0c0a5a323b1b250f821e87ac6bc3953742fa4e2b
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: 6f47453c38a22a4b03ba53e176786583208b6e09
        CONFIG_FILE: server.conf
      context: ./images/apache_httpd
    x-props:
      role: origin
  apache_httpd_h2_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 0c0a5a323b1b250f821e87ac6bc3953742fa4e2b
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: 6f47453c38a22a4b03ba53e176786583208b6e09
        BACKEND: echo
        CONFIG_FILE: proxy-h2.conf
      context: ./images/apache_httpd
    depends_on:
    - echo
    x-props:
      role: transducer
  apache_httpd_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 0c0a5a323b1b250f821e87ac6bc3953742fa4e2b
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: 6f47453c38a22a4b03ba53e176786583208b6e09
        BACKEND: echo
        CONFIG_FILE: proxy.conf
      context: ./images/apache_httpd
    depends_on:
    - echo
    x-props:
      role: transducer
  apache_tomcat:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/apache/tomcat
        APP_VERSION: c225172476c943f5a0f93b8f092dea7f35900e3c
      context: ./images/apache_tomcat
    x-props:
      role: origin
  apache_traffic_server:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/apache/trafficserver
        APP_VERSION: 3d04702a50f62d98304ed1e08c64751aebab5f57
        BACKEND: echo
        CACHE_CONFIG: cache.config
        RECORDS_YAML: records.yaml
        REMAP_CONFIG: remap.config
      context: ./images/apache_traffic_server
    depends_on:
    - echo
    x-props:
      role: transducer
  appweb:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/embedthis/appweb
        APP_VERSION: fae82cfc8913a1c0ec976a23cfd39fdbcee464c2
        CONFIG_FILE: server.conf
        MAKEME_BRANCH: master
        MAKEME_REPO: https://github.com/embedthis/makeme
        MAKEME_VERSION: 21a1c7df0da3063e44f99d0d3aabe1e0ad1d6161
      context: ./images/appweb
    x-props:
      role: origin
  appweb_proxy:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/embedthis/appweb
        APP_VERSION: fae82cfc8913a1c0ec976a23cfd39fdbcee464c2
        CONFIG_FILE: proxy.conf
        MAKEME_BRANCH: master
        MAKEME_REPO: https://github.com/embedthis/makeme
        MAKEME_VERSION: 21a1c7df0da3063e44f99d0d3aabe1e0ad1d6161
      context: ./images/appweb
    x-props:
      role: transducer
  aws_c_http:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/awslabs/aws-c-http
        APP_VERSION: ce0d65623bff28f03204756d9d1b3366bd0b387d
        AWS_C_CAL_BRANCH: main
        AWS_C_CAL_REPO: https://github.com/awslabs/aws-c-cal
        AWS_C_CAL_VERSION: b7b740262cfdcb65fa3c070e69b3cbc9cf79c001
        AWS_C_COMMON_BRANCH: main
        AWS_C_COMMON_REPO: https://github.com/awslabs/aws-c-common
        AWS_C_COMMON_VERSION: 2b67a658e461520f1de20d64342b91ddcedc7ebb
        AWS_C_COMPRESSION_BRANCH: main
        AWS_C_COMPRESSION_REPO: https://github.com/awslabs/aws-c-compression
        AWS_C_COMPRESSION_VERSION: d3b607c0efe6081669b2760c3dbb28087f29c65f
        AWS_C_IO_BRANCH: main
        AWS_C_IO_REPO: https://github.com/awslabs/aws-c-io
        AWS_C_IO_VERSION: 9c7f98dcb083bd705eeb323e77868b1e2c9d4e73
        AWS_LC_BRANCH: main
        AWS_LC_REPO: https://github.com/aws/aws-lc
        AWS_LC_VERSION: a435f20bd3f8734fb67dd67c27935ce0e55fe563
        S2N_TLS_BRANCH: main
        S2N_TLS_REPO: https://github.com/aws/s2n-tls
        S2N_TLS_VERSION: c15341ff7a0f0d8cc001a25eeac99989d2adccb0
      context: ./images/aws_c_http
    x-props:
      role: origin
  cpp_httplib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/yhirose/cpp-httplib
        APP_VERSION: ca5fe354fb83194bc72a676c4cc4136fca5316d0
      context: ./images/cpp_httplib
    x-props:
      role: origin
  dart_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/dart-lang/sdk
        APP_VERSION: 13e29e24ff4fc11147e43082c18dd65174899584
      context: ./images/dart_stdlib
    x-props:
      role: origin
  echo:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/narfindustries/http-garden
        APP_VERSION: abf9bdc2e2fc249cf2b9a812b937b614f827f516
      context: ./images/echo
  eclipse_grizzly:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/eclipse-ee4j/grizzly
        APP_VERSION: 6569c55261be0af1f41d8a66a004238df3f27239
      context: ./images/eclipse_grizzly
    x-props:
      port: 8080
      role: origin
  eclipse_jetty:
    build:
      args:
        APP_BRANCH: jetty-12.1.x
        APP_REPO: https://github.com/eclipse/jetty.project
        APP_VERSION: ca921d1b4a45d8bac2b01dfcf94384ab3c53a44b
      context: ./images/eclipse_jetty
    x-props:
      role: origin
  envoy:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 35696257099072798d4e1a9a6661928c16d18c5b
        BAZELISK_TAG: v1.26.0
        BACKEND: echo
        CONFIG_FILE: envoy.yaml
      context: ./images/envoy
    depends_on:
    - echo
    x-props:
      role: transducer
  envoy_h2:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 35696257099072798d4e1a9a6661928c16d18c5b
        BAZELISK_TAG: v1.26.0
        BACKEND: echo
        CONFIG_FILE: envoy-h2.yaml
      context: ./images/envoy
    depends_on:
    - echo
    x-props:
      role: transducer
  fasthttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/valyala/fasthttp
        APP_VERSION: dab027680cc57d7c2749ba018a72f8b943f473cc
      context: ./images/fasthttp
    x-props:
      role: origin
  go_stdlib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: app.go
        APP_VERSION: d71d8aeafd7aa5c2ff3da6a782acdd573a0409af
        GO_BOOTSTRAP_VERSION: 1.24.5
      context: ./images/go_stdlib
    x-props:
      role: origin
  go_stdlib_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: proxy.go
        APP_VERSION: d71d8aeafd7aa5c2ff3da6a782acdd573a0409af
        BACKEND: echo
        GO_BOOTSTRAP_VERSION: 1.24.5
      context: ./images/go_stdlib
    depends_on:
    - echo
    x-props:
      role: transducer
  gunicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/benoitc/gunicorn
        APP_VERSION: a86ea1e4e6c271d1cd1823c7e14490123f9238fe
      context: ./images/gunicorn
    x-props:
      role: origin
  h2o:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: db98b59ba7abfcd1dc9b43ea4b9ad1052aba775e
        CONFIG_FILE: h2o.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8326098f63eefabfa2b6ec595d90e9ed5ed958a
      context: ./images/h2o
    x-props:
      role: origin
  h2o_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: db98b59ba7abfcd1dc9b43ea4b9ad1052aba775e
        BACKEND: echo
        CONFIG_FILE: h2o-proxy.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8326098f63eefabfa2b6ec595d90e9ed5ed958a
      context: ./images/h2o
    depends_on:
    - echo
    x-props:
      role: transducer
  haproxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 2e5e6cdf23c70aaf4715c03615de333dc90d8285
        BACKEND: echo
        CONFIG_FILE: haproxy.conf
      context: ./images/haproxy
    depends_on:
    - echo
    x-props:
      role: transducer
  haproxy_fcgi:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 2e5e6cdf23c70aaf4715c03615de333dc90d8285
        CONFIG_FILE: haproxy-fcgi.conf
      context: ./images/haproxy
    x-props:
      role: origin
  haproxy_h2:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 2e5e6cdf23c70aaf4715c03615de333dc90d8285
        BACKEND: echo
        CONFIG_FILE: haproxy-h2.conf
      context: ./images/haproxy
    depends_on:
    - echo
    x-props:
      role: transducer
  http-garden-soil:
    build:
      args:
        CPYTHON_BRANCH: main
        CPYTHON_REPO: https://github.com/python/cpython
        CPYTHON_VERSION: d8fa40b08da60a711311751891fa830cb4ae77f3
      context: ./images/http-garden-soil
    image: http-garden-soil
  hyper:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/hyperium/hyper
        APP_VERSION: b8affd8a2ee5d77dec0c32050a7234e4f2f3751b
      context: ./images/hyper
    x-props:
      role: origin
  hypercorn:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/pgjones/hypercorn
        APP_VERSION: 6cb9c5cc11c5372d59ffb8348345e308bc2f1067
      context: ./images/hypercorn
    x-props:
      role: origin
  ktor:
    build:
      args:
        KOTLIN_COMPILER_ZIP_URL: https://github.com/JetBrains/kotlin/releases/download/v2.1.21/kotlin-compiler-2.1.21.zip
        APP_BRANCH: main
        APP_REPO: https://github.com/ktorio/ktor
        APP_VERSION: 92266d53ebcefe9c4caf033a41b41f0b2a81060f
      context: ./images/ktor
    x-props:
      role: origin
  libevent:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/libevent/libevent
        APP_VERSION: 112421c8fa4840acd73502f2ab6a674fc025de37
      context: ./images/libevent
    x-props:
      role: origin
  libmicrohttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.gnunet.org/libmicrohttpd.git
        APP_VERSION: f2e3bbda41c6263527808187c45f90b1704332f9
      context: ./images/libmicrohttpd
    x-props:
      role: origin
  libsoup:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://gitlab.gnome.org/GNOME/libsoup.git
        APP_VERSION: 1296cbf983f036f20262c453926dff77e1d6a852
      context: ./images/libsoup
    x-props:
      role: origin
  lighttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 9040a8afc9e9cc1b83ad8e065fb53912d09e147d
        CONFIG_FILE: server.conf
      context: ./images/lighttpd
    x-props:
      role: origin
  lighttpd_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 9040a8afc9e9cc1b83ad8e065fb53912d09e147d
        BACKEND: echo
        CONFIG_FILE: proxy.conf
      context: ./images/lighttpd
    depends_on:
    - echo
    x-props:
      role: transducer
  mongoose:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/cesanta/mongoose
        APP_VERSION: 58297a78718d1f14bfee11432cb3c02751774aa8
        SERVER_SOURCE: main.c
      context: ./images/mongoose
    x-props:
      role: origin
  netty:
    build:
      args:
        APP_BRANCH: 4.2
        APP_REPO: https://github.com/netty/netty
        APP_VERSION: 5d190b4d341785b7da959b38da9146eacee7a498
      context: ./images/netty
    x-props:
      role: origin
  nghttpx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nghttp2/nghttp2
        APP_VERSION: b81979f35b5b04a5399309a0f69a279190784b2e
        BACKEND: echo
      context: ./images/nghttpx
    depends_on:
    - echo
    x-props:
      role: transducer
  nghttpx_h2:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nghttp2/nghttp2
        APP_VERSION: b81979f35b5b04a5399309a0f69a279190784b2e
        BACKEND: echo
        PARAMS: ;;proto=h2
      context: ./images/nghttpx
    depends_on:
    - echo
    x-props:
      role: transducer
  nginx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 4da771108282cd233ddc37f83ba8bd01981beeb7
        CONFIG_FILE: nginx.conf
      context: ./images/nginx
    x-props:
      role: origin
  nginx_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 4da771108282cd233ddc37f83ba8bd01981beeb7
        BACKEND: echo
        CONFIG_FILE: nginx-proxy.conf
      context: ./images/nginx
    depends_on:
    - echo
    x-props:
      role: transducer
  node_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/nodejs/node
        APP_VERSION: d5b815c9ea59ef508c19281584f9276b1a4ef178
        SCRIPT: app.js
      context: ./images/node_stdlib
    x-props:
      role: origin
  node_stdlib_h2:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/nodejs/node
        APP_VERSION: d5b815c9ea59ef508c19281584f9276b1a4ef178
        SCRIPT: app_h2.js
      context: ./images/node_stdlib
    x-props:
      role: origin
  openbsd_httpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/kenballus/obhttpd-linux
        APP_VERSION: 175682bae865cc5c0d924382817b225374f0d19f
        OPENBSD_SRC_BRANCH: master
        OPENBSD_SRC_REPO: https://github.com/openbsd/src
        OPENBSD_SRC_VERSION: 24bd93804efe5f270bd4f5722bed599a9d57bd38
      context: ./images/openbsd_httpd
    x-props:
      role: origin
  openlitespeed:
    build:
      args:
        APP_BRANCH: v1.8.3.1
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 1.8.3
        CONFIG_FILE: server_config.conf
        VHOST_CONFIG_FILE: server_vhost.conf
      context: ./images/openlitespeed
    x-props:
      role: origin
      version_frozen: true
  openlitespeed_proxy:
    build:
      args:
        APP_BRANCH: v1.8.3.1
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 1.8.3
        BACKEND: echo
        CONFIG_FILE: proxy_config.conf
        VHOST_CONFIG_FILE: proxy_vhost.conf
      context: ./images/openlitespeed
    depends_on:
    - echo
    x-props:
      role: transducer
      version_frozen: true
  pound:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/graygnuorg/pound
        APP_VERSION: 4a0395616aa40caddf7ea5d35beee4c642c9ee60
        BACKEND: echo
      context: ./images/pound
    depends_on:
    - echo
    x-props:
      role: transducer
  protocol_http1:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/socketry/protocol-http1
        APP_VERSION: 58d22901b3d00030590a675203508dd71bca4628
      context: ./images/protocol_http1
    x-props:
      role: origin
      timeout: 0.2
  puma:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/puma/puma
        APP_VERSION: 97c7d129a940c809fb379b3ecf314d39a18a332b
      context: ./images/puma
    x-props:
      role: origin
  squid:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/squid-cache/squid
        APP_VERSION: 75418fdc2bcda8a4a81ea12ac84e02b3b425d9fc
        BACKEND: echo
      context: ./images/squid
    depends_on:
    - echo
    x-props:
      role: transducer
  tornado:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/tornadoweb/tornado
        APP_VERSION: 37417f8d4db9d9fbdebe90c85a85b530b8659542
      context: ./images/tornado
    x-props:
      role: origin
  twisted:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/twisted/twisted
        APP_VERSION: 6b52a3511644a7617102a9d004b90330bafbc151
      context: ./images/twisted
    x-props:
      role: origin
  undertow:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/undertow-io/undertow
        APP_VERSION: d099e7678b5364473152d9bc9e30a84eba69f6d3
      context: ./images/undertow
    x-props:
      role: origin
  uvicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/encode/uvicorn
        APP_VERSION: c1144fd4f130388cffc05ee17b08747ce8c1be11
      context: ./images/uvicorn
    x-props:
      role: origin
  varnish:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/varnishcache/varnish-cache
        APP_VERSION: 51a117587524cbdd59e43567e6cbd5a76e6a39ff
        BACKEND: echo
      context: ./images/varnish
    depends_on:
    - echo
    x-props:
      role: transducer
  waitress:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/Pylons/waitress
        APP_VERSION: 64c920fc9c85f4d0faf5687f3e86da66d1891975
      context: ./images/waitress
    x-props:
      role: origin
  webrick:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/ruby/webrick
        APP_VERSION: cfd6a1aa18ea29b2e78e6708caa70eba0e2e989e
      context: ./images/webrick
    x-props:
      role: origin
  yahns:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        CONFIG_FILE: server.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
      context: ./images/yahns
    x-props:
      role: origin
  yahns_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        BACKEND: echo
        CONFIG_FILE: proxy.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
      context: ./images/yahns
    depends_on:
    - echo
    x-props:
      role: transducer
