services:
  aiohttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/aio-libs/aiohttp
        APP_VERSION: e260b15ca8d5e3a199cc9db7d0d154b3cb7350d8
      context: ./images/aiohttp
    x-props:
      role: origin
  apache_httpd:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 3dffb297e99839f06cb9e7ad59096aadd2ece9da
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: c5d6918c7326f4870bd63624f7cda7f045f088df
        CONFIG_FILE: server.conf
        START_SCRIPT: start.sh
      context: ./images/apache_httpd
    x-props:
      role: origin
  apache_httpd_h2_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 3dffb297e99839f06cb9e7ad59096aadd2ece9da
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: c5d6918c7326f4870bd63624f7cda7f045f088df
        CONFIG_FILE: proxy-h2.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/apache_httpd
    x-props:
      role: h2_transducer
  apache_httpd_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 3dffb297e99839f06cb9e7ad59096aadd2ece9da
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: c5d6918c7326f4870bd63624f7cda7f045f088df
        CONFIG_FILE: proxy.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/apache_httpd
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  apache_tomcat:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/apache/tomcat
        APP_VERSION: 6abcfa58e0bbc55d4c64f8d72a4e707cb722a4ba
      context: ./images/apache_tomcat
    x-props:
      role: origin
  apache_traffic_server:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/apache/trafficserver
        APP_VERSION: c9fb43eac265779b820b60732f3f09809599a5bf
        CACHE_CONFIG: cache.config
        RECORDS_YAML: records.yaml
        REMAP_CONFIG: remap.config
      context: ./images/apache_traffic_server
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  appweb:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/embedthis/appweb
        APP_VERSION: dbc3edde45611f050cba6123d9f3847b7adc08e3
        CONFIG_FILE: server.conf
        MAKEME_BRANCH: master
        MAKEME_REPO: https://github.com/embedthis/makeme
        MAKEME_VERSION: 438feb90e24848746fdfe3e1dd87ac1d75d283c1
      context: ./images/appweb
    x-props:
      role: origin
  aws_c_http:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/awslabs/aws-c-http
        APP_VERSION: 283399e60dc99386875b5a6beb04fa6cb7922f00
        AWS_C_CAL_BRANCH: main
        AWS_C_CAL_REPO: https://github.com/awslabs/aws-c-cal
        AWS_C_CAL_VERSION: 3c6d901abf536928cd3775e46ea6bec5d47f4d51
        AWS_C_COMMON_BRANCH: main
        AWS_C_COMMON_REPO: https://github.com/awslabs/aws-c-common
        AWS_C_COMMON_VERSION: a7e70ebf422f772411b47e6753169ee339be6a6d
        AWS_C_COMPRESSION_BRANCH: main
        AWS_C_COMPRESSION_REPO: https://github.com/awslabs/aws-c-compression
        AWS_C_COMPRESSION_VERSION: d8264e64f698341eb03039b96b4f44702a9b3f83
        AWS_C_IO_BRANCH: main
        AWS_C_IO_REPO: https://github.com/awslabs/aws-c-io
        AWS_C_IO_VERSION: 8906a02cb204b0b01cd38c2c2d62d7312dbee50f
        AWS_LC_BRANCH: main
        AWS_LC_REPO: https://github.com/aws/aws-lc
        AWS_LC_VERSION: 1f7577b8a9324230616da692cfe78772ee4753b4
        S2N_TLS_BRANCH: main
        S2N_TLS_REPO: https://github.com/aws/s2n-tls
        S2N_TLS_VERSION: 389e627dc423207d15ae1f74057ef0ac04641f23
      context: ./images/aws_c_http
    x-props:
      role: origin
  cpp_httplib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/yhirose/cpp-httplib
        APP_VERSION: 35c52c1ab9b8ade2e66548fcec5e417092d8e583
      context: ./images/cpp_httplib
    x-props:
      role: origin
  eclipse_grizzly:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/eclipse-ee4j/grizzly
        APP_VERSION: 59d756a58c909617d538d3d0fc2629f2d926a8f4
      context: ./images/eclipse_grizzly
    x-props:
      role: origin
  eclipse_jetty:
    build:
      args:
        APP_BRANCH: jetty-12.1.x
        APP_REPO: https://github.com/eclipse/jetty.project
        APP_VERSION: e38b0a318ab6d534186d16b33b057db95a22e906
      context: ./images/eclipse_jetty
    x-props:
      role: origin
  envoy:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 39744b212c5fe2a75a7201815cc8f233a24c3266
        BAZELISK_TAG: v1.26.0
        CONFIG_FILE: envoy.yaml
      context: ./images/envoy
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  envoy_h2:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 39744b212c5fe2a75a7201815cc8f233a24c3266
        BAZELISK_TAG: v1.26.0
        CONFIG_FILE: envoy-h2.yaml
      context: ./images/envoy
    x-props:
      role: h2_transducer
  fasthttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/valyala/fasthttp
        APP_VERSION: 3a2fdec290176325d5432245facf04ef25674f46
      context: ./images/fasthttp
    x-props:
      role: origin
  go_stdlib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: app.go
        APP_VERSION: 1cd71689f2ed8f07031a0cc58fc3586ca501839f
        GO_BOOTSTRAP_VERSION: 1.25.0
        START_SCRIPT: start.sh
      context: ./images/go_stdlib
    x-props:
      requires-tls: true
      role: origin
  go_stdlib_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: proxy.go
        APP_VERSION: 1cd71689f2ed8f07031a0cc58fc3586ca501839f
        GO_BOOTSTRAP_VERSION: 1.25.0
        START_SCRIPT: start_proxy.sh
      context: ./images/go_stdlib
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  gunicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/benoitc/gunicorn
        APP_VERSION: 56b5ad87f8d72a674145c273ed8f547513c2b409
      context: ./images/gunicorn
    x-props:
      role: origin
  h2o:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: c58132197415a3cf285230de9c38940de48f5051
        CONFIG_FILE: h2o.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8326098f63eefabfa2b6ec595d90e9ed5ed958a
        START_SCRIPT: start.sh
      context: ./images/h2o
    x-props:
      requires-tls: true
      role: origin
  h2o_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: c58132197415a3cf285230de9c38940de48f5051
        CONFIG_FILE: h2o-proxy.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8326098f63eefabfa2b6ec595d90e9ed5ed958a
        START_SCRIPT: start_proxy.sh
      context: ./images/h2o
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  haproxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: b706f2d092b02e8e37662d407d3a2a4914872988
        CONFIG_FILE: haproxy.conf
        START_SCRIPT: start.sh
      context: ./images/haproxy
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  haproxy_fcgi:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: b706f2d092b02e8e37662d407d3a2a4914872988
        CONFIG_FILE: haproxy-fcgi.conf
        START_SCRIPT: start_fcgi.sh
      context: ./images/haproxy
    x-props:
      role: origin
  haproxy_h2:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: b706f2d092b02e8e37662d407d3a2a4914872988
        CONFIG_FILE: haproxy-h2.conf
        START_SCRIPT: start.sh
      context: ./images/haproxy
    x-props:
      role: h2_transducer
  hyper:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/hyperium/hyper
        APP_VERSION: f9f8f44058745d23fa52abf51b96b61ee7665642
        HYPER_UTIL_BRANCH: master
        HYPER_UTIL_REPO: https://github.com/hyperium/hyper-util
        HYPER_UTIL_VERSION: 66afc93debef02548c86e8454e6bc01cf4fca280
      context: ./images/hyper
    x-props:
      role: origin
  hypercorn:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/pgjones/hypercorn
        APP_VERSION: 6cb9c5cc11c5372d59ffb8348345e308bc2f1067
      context: ./images/hypercorn
    x-props:
      requires-tls: true
      role: origin
  ktor:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/ktorio/ktor
        APP_VERSION: 84e3b98dff054448fdfdd25918e9f379be3d4d1f
        KOTLIN_COMPILER_ZIP_URL: https://github.com/JetBrains/kotlin/releases/download/v2.1.21/kotlin-compiler-2.1.21.zip
      context: ./images/ktor
    x-props:
      role: origin
  libevent:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/libevent/libevent
        APP_VERSION: 112421c8fa4840acd73502f2ab6a674fc025de37
      context: ./images/libevent
    x-props:
      role: origin
  libmicrohttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.gnunet.org/libmicrohttpd.git
        APP_VERSION: ba8f88fcb47cfb0de5237d47f9487cd1f350cbe9
      context: ./images/libmicrohttpd
    x-props:
      role: origin
  libsoup:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://gitlab.gnome.org/GNOME/libsoup.git
        APP_VERSION: 00637c64ae9bf5b6e488fc535346a2fef4740798
      context: ./images/libsoup
    x-props:
      role: origin
  lighttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 5aa79652fd52c57427a30d73802578c6e44ee69c
        CONFIG_FILE: server.conf
        START_SCRIPT: start.sh
      context: ./images/lighttpd
    x-props:
      role: origin
  lighttpd_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 5aa79652fd52c57427a30d73802578c6e44ee69c
        CONFIG_FILE: proxy.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/lighttpd
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  mongoose:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/cesanta/mongoose
        APP_VERSION: 235dafe646e1e023f8cc55bb888b7496ee83afb9
        SERVER_SOURCE: main.c
      context: ./images/mongoose
    x-props:
      role: origin
  netty:
    build:
      args:
        APP_BRANCH: 4.2
        APP_REPO: https://github.com/netty/netty
        APP_VERSION: 3b5c23ddd8e18726ad5d598c707ee27c46ab8ac3
      context: ./images/netty
    x-props:
      role: origin
  nghttpx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nghttp2/nghttp2
        APP_VERSION: 2f1565b0e2385094ad90596960e99a7c573e40bd
      context: ./images/nghttpx
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  nghttpx_h2:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nghttp2/nghttp2
        APP_VERSION: 2f1565b0e2385094ad90596960e99a7c573e40bd
        PARAMS: ;;proto=h2
      context: ./images/nghttpx
    x-props:
      role: h2_transducer
  nginx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 78d1ab5a2c00839a36ff6bac661d9785fce3c1a4
        CONFIG_FILE: nginx.conf
        START_SCRIPT: start.sh
      context: ./images/nginx
    x-props:
      role: origin
  nginx_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 78d1ab5a2c00839a36ff6bac661d9785fce3c1a4
        CONFIG_FILE: nginx-proxy.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/nginx
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  node_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/nodejs/node
        APP_VERSION: d54e6aec9ee4a45aab148bbb6ba825f67c38ec6f
        SCRIPT: app.js
      context: ./images/node_stdlib
    x-props:
      requires-tls: true
      role: origin
  openbsd_httpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/kenballus/obhttpd-linux
        APP_VERSION: 13177feda2e869a13b07221385e850d07b3f16b1
        OPENBSD_SRC_BRANCH: master
        OPENBSD_SRC_REPO: https://github.com/openbsd/src
        OPENBSD_SRC_VERSION: 514aadd59570854e1025db3ca8b0087d9bdd842f
      context: ./images/openbsd_httpd
    x-props:
      role: origin
  openlitespeed:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: da5f2e7c1dd2c1cdf5e102c76941b2ad429773b9
        CONFIG_FILE: server_config.conf
        START_SCRIPT: start.sh
        VHOST_CONFIG_FILE: server_vhost.conf
      context: ./images/openlitespeed
    x-props:
      role: origin
  openlitespeed_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: da5f2e7c1dd2c1cdf5e102c76941b2ad429773b9
        CONFIG_FILE: proxy_config.conf
        START_SCRIPT: start_proxy.sh
        VHOST_CONFIG_FILE: proxy_vhost.conf
      context: ./images/openlitespeed
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  openwrt_uhttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.openwrt.org/project/uhttpd.git
        APP_VERSION: ebb92e6b339b88bbc6b76501b6603c52d4887ba1
        LIBUBOX_BRANCH: master
        LIBUBOX_REPO: https://git.openwrt.org/project/libubox.git
        LIBUBOX_VERSION: 61cc1e6fdc0eec075869e1d4d2e6e98c10856b97
        LIBUBUS_BRANCH: master
        LIBUBUS_REPO: https://git.openwrt.org/project/ubus.git
        LIBUBUS_VERSION: f247c18f8a552b87f74427df5ef8c43f8f942628
        UCODE_BRANCH: master
        UCODE_REPO: https://github.com/jow-/ucode
        UCODE_VERSION: 5416dcfec9ea6326ee79a82da3e103a39ecf59aa
        USTREAM_SSL_BRANCH: master
        USTREAM_SSL_REPO: https://git.openwrt.org/project/ustream-ssl.git
        USTREAM_SSL_VERSION: 5a81c108d20e24724ed847cc4be033f2a74e6635
      context: ./images/openwrt_uhttpd
    x-props:
      role: origin
  pingora:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/cloudflare/pingora
        APP_VERSION: 850946086215596151ee96f6b2865ce3dfce65ab
      context: ./images/pingora
    x-props:
      role: origin
  pound:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/graygnuorg/pound
        APP_VERSION: f8eb97c75910da84f41e47b8c519ee16970407d4
      context: ./images/pound
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  protocol_http1:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/socketry/protocol-http1
        APP_VERSION: 5b2149ccfd938f3e8d91a9b9f182e790fc5ae92b
      context: ./images/protocol_http1
    x-props:
      role: origin
  puma:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/puma/puma
        APP_VERSION: a5206f1acdb953f87e690909d4434bb7e0b134af
      context: ./images/puma
    x-props:
      role: origin
  squid:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/squid-cache/squid
        APP_VERSION: e7e9073a2435cc93b913553d147b497fda77c1ab
      context: ./images/squid
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  tornado:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/tornadoweb/tornado
        APP_VERSION: d30ef74020924be5f214091de95314ca3ce919af
      context: ./images/tornado
    x-props:
      role: origin
  twisted:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/twisted/twisted
        APP_VERSION: ffb0ab707acbe1284e2f45c7a16e325ed27a3d99
      context: ./images/twisted
    x-props:
      role: origin
  undertow:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/undertow-io/undertow
        APP_VERSION: 750bc625c66da6073bfc47748c76000071bcf3fb
      context: ./images/undertow
    x-props:
      role: origin
  uvicorn:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/Kludex/uvicorn
        APP_VERSION: 93d95107490d5ea3693601388d7783c450058271
      context: ./images/uvicorn
    x-props:
      role: origin
  varnish:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/varnishcache/varnish-cache
        APP_VERSION: 9f02342b455469349e24a88e49550f23c262baaf
      context: ./images/varnish
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  waitress:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/Pylons/waitress
        APP_VERSION: 64c920fc9c85f4d0faf5687f3e86da66d1891975
      context: ./images/waitress
    x-props:
      role: origin
  webrick:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/ruby/webrick
        APP_VERSION: 6c95f0c4b9ee559de02cd9435e33614d249456be
      context: ./images/webrick
    x-props:
      role: origin
  yahns:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        CONFIG_FILE: server.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
        START_SCRIPT: start.sh
      context: ./images/yahns
    x-props:
      role: origin
  yahns_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        CONFIG_FILE: proxy.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
        START_SCRIPT: start_proxy.sh
      context: ./images/yahns
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
