services:
  aiohttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/aio-libs/aiohttp
        APP_VERSION: f6941e738fd5f8b3b110dcf7d1e63ee41de86a70
      context: ./images/aiohttp
    x-props:
      role: origin
  apache_httpd:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 0c0a5a323b1b250f821e87ac6bc3953742fa4e2b
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: 34686fa9b38334db4ed21a390d3ce6af5640b087
        CONFIG_FILE: server.conf
      context: ./images/apache_httpd
    x-props:
      role: origin
  apache_httpd_h2_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 0c0a5a323b1b250f821e87ac6bc3953742fa4e2b
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: 34686fa9b38334db4ed21a390d3ce6af5640b087
        CONFIG_FILE: proxy-h2.conf
      context: ./images/apache_httpd
    x-props:
      role: h2_transducer
  apache_httpd_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 0c0a5a323b1b250f821e87ac6bc3953742fa4e2b
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: 34686fa9b38334db4ed21a390d3ce6af5640b087
        CONFIG_FILE: proxy.conf
      context: ./images/apache_httpd
    x-props:
      role: transducer
  apache_tomcat:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/apache/tomcat
        APP_VERSION: 89770f2143394a912599e29bb585e16c205f9bef
      context: ./images/apache_tomcat
    x-props:
      role: origin
  apache_traffic_server:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/apache/trafficserver
        APP_VERSION: 447a2a01961c4c1896f7a2b6c66eb4aefad07496
        CACHE_CONFIG: cache.config
        RECORDS_YAML: records.yaml
        REMAP_CONFIG: remap.config
      context: ./images/apache_traffic_server
    x-props:
      role: transducer
  appweb:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/embedthis/appweb
        APP_VERSION: fae82cfc8913a1c0ec976a23cfd39fdbcee464c2
        CONFIG_FILE: server.conf
        MAKEME_BRANCH: master
        MAKEME_REPO: https://github.com/embedthis/makeme
        MAKEME_VERSION: 21a1c7df0da3063e44f99d0d3aabe1e0ad1d6161
      context: ./images/appweb
    x-props:
      role: origin
  aws_c_http:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/awslabs/aws-c-http
        APP_VERSION: ce0d65623bff28f03204756d9d1b3366bd0b387d
        AWS_C_CAL_BRANCH: main
        AWS_C_CAL_REPO: https://github.com/awslabs/aws-c-cal
        AWS_C_CAL_VERSION: b7b740262cfdcb65fa3c070e69b3cbc9cf79c001
        AWS_C_COMMON_BRANCH: main
        AWS_C_COMMON_REPO: https://github.com/awslabs/aws-c-common
        AWS_C_COMMON_VERSION: 2b67a658e461520f1de20d64342b91ddcedc7ebb
        AWS_C_COMPRESSION_BRANCH: main
        AWS_C_COMPRESSION_REPO: https://github.com/awslabs/aws-c-compression
        AWS_C_COMPRESSION_VERSION: d3b607c0efe6081669b2760c3dbb28087f29c65f
        AWS_C_IO_BRANCH: main
        AWS_C_IO_REPO: https://github.com/awslabs/aws-c-io
        AWS_C_IO_VERSION: 9c7f98dcb083bd705eeb323e77868b1e2c9d4e73
        AWS_LC_BRANCH: main
        AWS_LC_REPO: https://github.com/aws/aws-lc
        AWS_LC_VERSION: 1a5b9eb7e97b8e0ea75d5e045bd7fbb01cbb38e1
        S2N_TLS_BRANCH: main
        S2N_TLS_REPO: https://github.com/aws/s2n-tls
        S2N_TLS_VERSION: 418313c274d9cb72984dcd6e5e917740bc180664
      context: ./images/aws_c_http
    x-props:
      role: origin
  cpp_httplib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/yhirose/cpp-httplib
        APP_VERSION: 0b3758ec36bea9ec567aedc8fa1cacbdbc3a83d6
      context: ./images/cpp_httplib
    x-props:
      role: origin
  eclipse_grizzly:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/eclipse-ee4j/grizzly
        APP_VERSION: 6569c55261be0af1f41d8a66a004238df3f27239
      context: ./images/eclipse_grizzly
    x-props:
      port: 8080
      role: origin
  eclipse_jetty:
    build:
      args:
        APP_BRANCH: jetty-12.1.x
        APP_REPO: https://github.com/eclipse/jetty.project
        APP_VERSION: fae9272a4cbd8e19742d851bcdbbf5791babf58e
      context: ./images/eclipse_jetty
    x-props:
      role: origin
  envoy:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 001b8595e084db6f469596ef6aa7f0aac2f001a8
        BAZELISK_TAG: v1.26.0
        CONFIG_FILE: envoy.yaml
      context: ./images/envoy
    x-props:
      role: transducer
  envoy_h2:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 001b8595e084db6f469596ef6aa7f0aac2f001a8
        BAZELISK_TAG: v1.26.0
        CONFIG_FILE: envoy-h2.yaml
      context: ./images/envoy
    x-props:
      role: h2_transducer
  fasthttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/valyala/fasthttp
        APP_VERSION: 01d533ad1561d9f2b8878f14e2267e12fc37db1a
      context: ./images/fasthttp
    x-props:
      role: origin
  go_stdlib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: app.go
        APP_VERSION: eb7f515c4d920c884ba7c37939f016a153c466e9
        GO_BOOTSTRAP_VERSION: 1.24.5
      context: ./images/go_stdlib
    x-props:
      role: origin
  go_stdlib_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: proxy.go
        APP_VERSION: eb7f515c4d920c884ba7c37939f016a153c466e9
        GO_BOOTSTRAP_VERSION: 1.24.5
      context: ./images/go_stdlib
    x-props:
      role: transducer
  gunicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/benoitc/gunicorn
        APP_VERSION: a86ea1e4e6c271d1cd1823c7e14490123f9238fe
      context: ./images/gunicorn
    x-props:
      role: origin
  h2o:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: db98b59ba7abfcd1dc9b43ea4b9ad1052aba775e
        CONFIG_FILE: h2o.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8326098f63eefabfa2b6ec595d90e9ed5ed958a
      context: ./images/h2o
    x-props:
      role: origin
  h2o_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: db98b59ba7abfcd1dc9b43ea4b9ad1052aba775e
        CONFIG_FILE: h2o-proxy.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8326098f63eefabfa2b6ec595d90e9ed5ed958a
      context: ./images/h2o
    x-props:
      role: transducer
  haproxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 365a69648c70ec35459266bf76de91114685260d
        CONFIG_FILE: haproxy.conf
      context: ./images/haproxy
    volumes:
      - ./tools:/tools
    x-props:
      role: transducer
  haproxy_fcgi:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 365a69648c70ec35459266bf76de91114685260d
        CONFIG_FILE: haproxy-fcgi.conf
      context: ./images/haproxy
    x-props:
      role: origin
  haproxy_h2:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 365a69648c70ec35459266bf76de91114685260d
        CONFIG_FILE: haproxy-h2.conf
      context: ./images/haproxy
    x-props:
      role: h2_transducer
  hyper:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/hyperium/hyper
        APP_VERSION: 974289fb3dc40db87f7e759c27cdba4e1eb407d4
      context: ./images/hyper
    x-props:
      role: origin
  hypercorn:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/pgjones/hypercorn
        APP_VERSION: 6cb9c5cc11c5372d59ffb8348345e308bc2f1067
      context: ./images/hypercorn
    x-props:
      role: origin
  ktor:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/ktorio/ktor
        APP_VERSION: ff2efa7492179e86948be9c9d772be3414b00c97
        KOTLIN_COMPILER_ZIP_URL: https://github.com/JetBrains/kotlin/releases/download/v2.1.21/kotlin-compiler-2.1.21.zip
      context: ./images/ktor
    x-props:
      role: origin
  libevent:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/libevent/libevent
        APP_VERSION: 112421c8fa4840acd73502f2ab6a674fc025de37
      context: ./images/libevent
    x-props:
      role: origin
  libmicrohttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.gnunet.org/libmicrohttpd.git
        APP_VERSION: f2e3bbda41c6263527808187c45f90b1704332f9
      context: ./images/libmicrohttpd
    x-props:
      role: origin
  libsoup:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://gitlab.gnome.org/GNOME/libsoup.git
        APP_VERSION: 1296cbf983f036f20262c453926dff77e1d6a852
      context: ./images/libsoup
    x-props:
      role: origin
  lighttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 9040a8afc9e9cc1b83ad8e065fb53912d09e147d
        CONFIG_FILE: server.conf
      context: ./images/lighttpd
    x-props:
      role: origin
  lighttpd_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 9040a8afc9e9cc1b83ad8e065fb53912d09e147d
        CONFIG_FILE: proxy.conf
      context: ./images/lighttpd
    x-props:
      role: transducer
  mongoose:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/cesanta/mongoose
        APP_VERSION: b19cf8654fffc903c7ff1941181c20c1f15f0170
        SERVER_SOURCE: main.c
      context: ./images/mongoose
    x-props:
      role: origin
  netty:
    build:
      args:
        APP_BRANCH: 4.2
        APP_REPO: https://github.com/netty/netty
        APP_VERSION: 6e1bd0fd09d13c93d64ad023cd54f3c6db1715e5
      context: ./images/netty
    x-props:
      role: origin
  nghttpx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nghttp2/nghttp2
        APP_VERSION: d8d94e7a6916db1bd14243799fe933965bfe7dd7
      context: ./images/nghttpx
    x-props:
      role: transducer
  nghttpx_h2:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nghttp2/nghttp2
        APP_VERSION: d8d94e7a6916db1bd14243799fe933965bfe7dd7
        PARAMS: ;;proto=h2
      context: ./images/nghttpx
    x-props:
      role: h2_transducer
  nginx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 50932c3c6c1d2c442ef08241443162c7a3ed58b3
        CONFIG_FILE: nginx.conf
      context: ./images/nginx
    x-props:
      role: origin
  nginx_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 50932c3c6c1d2c442ef08241443162c7a3ed58b3
        CONFIG_FILE: nginx-proxy.conf
      context: ./images/nginx
    x-props:
      role: transducer
  node_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/nodejs/node
        APP_VERSION: 5f5f9cb0150ce74a5f03be044e0019f3a3c27bba
        SCRIPT: app.js
      context: ./images/node_stdlib
    x-props:
      role: origin
  node_stdlib_h2:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/nodejs/node
        APP_VERSION: 5f5f9cb0150ce74a5f03be044e0019f3a3c27bba
        SCRIPT: app_h2.js
      context: ./images/node_stdlib
    x-props:
      role: h2_origin
  openbsd_httpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/kenballus/obhttpd-linux
        APP_VERSION: 175682bae865cc5c0d924382817b225374f0d19f
        OPENBSD_SRC_BRANCH: master
        OPENBSD_SRC_REPO: https://github.com/openbsd/src
        OPENBSD_SRC_VERSION: 42d94468ffbea20a44a659781cdaf9e56c9bb130
      context: ./images/openbsd_httpd
    x-props:
      role: origin
  openlitespeed:
    build:
      args:
        APP_BRANCH: v1.8.3.1
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 1.8.3
        CONFIG_FILE: server_config.conf
        VHOST_CONFIG_FILE: server_vhost.conf
      context: ./images/openlitespeed
    x-props:
      role: origin
      version_frozen: true
  openlitespeed_proxy:
    build:
      args:
        APP_BRANCH: v1.8.3.1
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 1.8.3
        CONFIG_FILE: proxy_config.conf
        VHOST_CONFIG_FILE: proxy_vhost.conf
      context: ./images/openlitespeed
    x-props:
      role: transducer
      version_frozen: true
  pound:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/graygnuorg/pound
        APP_VERSION: 5d2c985ed5582cf26b151095d9fc3f0c31751e9d
      context: ./images/pound
    x-props:
      role: transducer
  protocol_http1:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/socketry/protocol-http1
        APP_VERSION: 58d22901b3d00030590a675203508dd71bca4628
      context: ./images/protocol_http1
    x-props:
      role: origin
      timeout: 0.2
  puma:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/puma/puma
        APP_VERSION: 4e60f73d857f65e6a5800fc0b4c6286a864d1811
      context: ./images/puma
    x-props:
      role: origin
  squid:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/squid-cache/squid
        APP_VERSION: bfc9f840a22113a656390fd7c8fc18c664491302
      context: ./images/squid
    x-props:
      role: transducer
  tornado:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/tornadoweb/tornado
        APP_VERSION: 37417f8d4db9d9fbdebe90c85a85b530b8659542
      context: ./images/tornado
    x-props:
      role: origin
  twisted:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/twisted/twisted
        APP_VERSION: 8b87d664b6d5b02887bf3737c09b8042256cc234
      context: ./images/twisted
    x-props:
      role: origin
  undertow:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/undertow-io/undertow
        APP_VERSION: 089dad4c7a1c095541c0529c86edc13cada7362d
      context: ./images/undertow
    x-props:
      role: origin
  uvicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/encode/uvicorn
        APP_VERSION: c1144fd4f130388cffc05ee17b08747ce8c1be11
      context: ./images/uvicorn
    x-props:
      role: origin
  varnish:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/varnishcache/varnish-cache
        APP_VERSION: 09cd9d4be60e6d09ee9915ced766c596c8482ac0
      context: ./images/varnish
    x-props:
      role: transducer
  waitress:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/Pylons/waitress
        APP_VERSION: 64c920fc9c85f4d0faf5687f3e86da66d1891975
      context: ./images/waitress
    x-props:
      role: origin
  webrick:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/ruby/webrick
        APP_VERSION: aca2e287b5c09fd8dfc81ffbb737a26b0c410f6b
      context: ./images/webrick
    x-props:
      role: origin
  yahns:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        CONFIG_FILE: server.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
      context: ./images/yahns
    x-props:
      role: origin
  yahns_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        CONFIG_FILE: proxy.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
      context: ./images/yahns
    x-props:
      role: transducer
