services:
  aiohttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/aio-libs/aiohttp
        APP_VERSION: 16f565aff665264875849add3bf16ae6720d1617
      context: ./images/aiohttp
    x-props:
      role: origin
  apache_httpd:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: a6dcd191f4f168e06ccaac55edaeca5d02b4a791
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: c75d7ea1e4b3d6d2cc115bec7e9a732cfc96ec68
        CONFIG_FILE: server.conf
        START_SCRIPT: start.sh
      context: ./images/apache_httpd
    x-props:
      role: origin
  apache_httpd_h2_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: a6dcd191f4f168e06ccaac55edaeca5d02b4a791
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: c75d7ea1e4b3d6d2cc115bec7e9a732cfc96ec68
        CONFIG_FILE: proxy-h2.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/apache_httpd
    x-props:
      role: h2_transducer
  apache_httpd_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: a6dcd191f4f168e06ccaac55edaeca5d02b4a791
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: c75d7ea1e4b3d6d2cc115bec7e9a732cfc96ec68
        CONFIG_FILE: proxy.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/apache_httpd
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  apache_tomcat:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/apache/tomcat
        APP_VERSION: 7ca57ebd83fbcac230d2aa74885e553b6fd6b17f
      context: ./images/apache_tomcat
    x-props:
      role: origin
  apache_traffic_server:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/apache/trafficserver
        APP_VERSION: 83adab4eaf1aa1c1504fb6ba5a22df413134cd26
        CACHE_CONFIG: cache.config
        RECORDS_YAML: records.yaml
        REMAP_CONFIG: remap.config
      context: ./images/apache_traffic_server
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  appweb:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/embedthis/appweb
        APP_VERSION: fae82cfc8913a1c0ec976a23cfd39fdbcee464c2
        CONFIG_FILE: server.conf
        MAKEME_BRANCH: master
        MAKEME_REPO: https://github.com/embedthis/makeme
        MAKEME_VERSION: 21a1c7df0da3063e44f99d0d3aabe1e0ad1d6161
      context: ./images/appweb
    x-props:
      role: origin
  aws_c_http:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/awslabs/aws-c-http
        APP_VERSION: 283399e60dc99386875b5a6beb04fa6cb7922f00
        AWS_C_CAL_BRANCH: main
        AWS_C_CAL_REPO: https://github.com/awslabs/aws-c-cal
        AWS_C_CAL_VERSION: c3fd3ed584a84f4fd758e3f41fba223e36579d0a
        AWS_C_COMMON_BRANCH: main
        AWS_C_COMMON_REPO: https://github.com/awslabs/aws-c-common
        AWS_C_COMMON_VERSION: cde20c682d46ed8ee03ab6412c3f386f5dbdd0c7
        AWS_C_COMPRESSION_BRANCH: main
        AWS_C_COMPRESSION_REPO: https://github.com/awslabs/aws-c-compression
        AWS_C_COMPRESSION_VERSION: d8264e64f698341eb03039b96b4f44702a9b3f83
        AWS_C_IO_BRANCH: main
        AWS_C_IO_REPO: https://github.com/awslabs/aws-c-io
        AWS_C_IO_VERSION: db7a1bddc9a29eca18734d0af189c3924775dcf1
        AWS_LC_BRANCH: main
        AWS_LC_REPO: https://github.com/aws/aws-lc
        AWS_LC_VERSION: 2c04af88df71a05f776ad38be13cde46606f5f16
        S2N_TLS_BRANCH: main
        S2N_TLS_REPO: https://github.com/aws/s2n-tls
        S2N_TLS_VERSION: 8adb893580a2f28eb8873c1ede707cc3ddfec539
      context: ./images/aws_c_http
    x-props:
      role: origin
  cpp_httplib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/yhirose/cpp-httplib
        APP_VERSION: 89c932f313c6437c38f2982869beacc89c2f2246
      context: ./images/cpp_httplib
    x-props:
      role: origin
  eclipse_grizzly:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/eclipse-ee4j/grizzly
        APP_VERSION: 7ea0c5745bd0d65d4a939fa33a7930faf8603cf4
      context: ./images/eclipse_grizzly
    x-props:
      role: origin
  eclipse_jetty:
    build:
      args:
        APP_BRANCH: jetty-12.1.x
        APP_REPO: https://github.com/eclipse/jetty.project
        APP_VERSION: ecacde4983cda4274e3102684276b585fcfc21d5
      context: ./images/eclipse_jetty
    x-props:
      role: origin
  envoy:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 0f7d63e81474266339e492213a334f41772a5486
        BAZELISK_TAG: v1.26.0
        CONFIG_FILE: envoy.yaml
      context: ./images/envoy
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  envoy_h2:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 0f7d63e81474266339e492213a334f41772a5486
        BAZELISK_TAG: v1.26.0
        CONFIG_FILE: envoy-h2.yaml
      context: ./images/envoy
    x-props:
      role: h2_transducer
  fasthttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/valyala/fasthttp
        APP_VERSION: e9640b4d39215ac87fa85c171b26d745a40a8e99
      context: ./images/fasthttp
    x-props:
      role: origin
  go_stdlib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: app.go
        APP_VERSION: de5d7eccb99088e3ab42c0d907da6852d8f9cebe
        GO_BOOTSTRAP_VERSION: 1.25.0
        START_SCRIPT: start.sh
      context: ./images/go_stdlib
    x-props:
      requires-tls: true
      role: origin
  go_stdlib_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: proxy.go
        APP_VERSION: de5d7eccb99088e3ab42c0d907da6852d8f9cebe
        GO_BOOTSTRAP_VERSION: 1.25.0
        START_SCRIPT: start_proxy.sh
      context: ./images/go_stdlib
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  gunicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/benoitc/gunicorn
        APP_VERSION: a86ea1e4e6c271d1cd1823c7e14490123f9238fe
      context: ./images/gunicorn
    x-props:
      role: origin
  h2o:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: 3b9b6a53cac8bcc6a25fb28df81ad295fc5f9402
        CONFIG_FILE: h2o.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8326098f63eefabfa2b6ec595d90e9ed5ed958a
        START_SCRIPT: start.sh
      context: ./images/h2o
    x-props:
      requires-tls: true
      role: origin
  h2o_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: 3b9b6a53cac8bcc6a25fb28df81ad295fc5f9402
        CONFIG_FILE: h2o-proxy.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8326098f63eefabfa2b6ec595d90e9ed5ed958a
        START_SCRIPT: start_proxy.sh
      context: ./images/h2o
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  haproxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: be417c1db25bdf59a5d288e1feda146df8cd4fb8
        CONFIG_FILE: haproxy.conf
        START_SCRIPT: start.sh
      context: ./images/haproxy
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  haproxy_fcgi:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: be417c1db25bdf59a5d288e1feda146df8cd4fb8
        CONFIG_FILE: haproxy-fcgi.conf
        START_SCRIPT: start_fcgi.sh
      context: ./images/haproxy
    x-props:
      role: origin
  haproxy_h2:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: be417c1db25bdf59a5d288e1feda146df8cd4fb8
        CONFIG_FILE: haproxy-h2.conf
        START_SCRIPT: start.sh
      context: ./images/haproxy
    x-props:
      role: h2_transducer
  hyper:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/hyperium/hyper
        APP_VERSION: f9f8f44058745d23fa52abf51b96b61ee7665642
        HYPER_UTIL_BRANCH: master
        HYPER_UTIL_REPO: https://github.com/hyperium/hyper-util
        HYPER_UTIL_VERSION: 00035bac2da1cfa820eda4db7bf7ddcbd30be3c1
      context: ./images/hyper
    x-props:
      role: origin
  hypercorn:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/pgjones/hypercorn
        APP_VERSION: 6cb9c5cc11c5372d59ffb8348345e308bc2f1067
      context: ./images/hypercorn
    x-props:
      requires-tls: true
      role: origin
  ktor:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/ktorio/ktor
        APP_VERSION: 55e77cff55cbce5d19cc402a5219ebd1081fd0a8
        KOTLIN_COMPILER_ZIP_URL: https://github.com/JetBrains/kotlin/releases/download/v2.1.21/kotlin-compiler-2.1.21.zip
      context: ./images/ktor
    x-props:
      role: origin
  libevent:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/libevent/libevent
        APP_VERSION: 112421c8fa4840acd73502f2ab6a674fc025de37
      context: ./images/libevent
    x-props:
      role: origin
  libmicrohttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.gnunet.org/libmicrohttpd.git
        APP_VERSION: 1fd9b3779f58e2f3385f9fdd5df8761fb991508e
      context: ./images/libmicrohttpd
    x-props:
      role: origin
  libsoup:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://gitlab.gnome.org/GNOME/libsoup.git
        APP_VERSION: b3df7199959e8661d6cf9d65ffbfb94692982b3a
      context: ./images/libsoup
    x-props:
      role: origin
  lighttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 48c5d482a0d285f25244a63a14bfb306f71da81f
        CONFIG_FILE: server.conf
        START_SCRIPT: start.sh
      context: ./images/lighttpd
    x-props:
      role: origin
  lighttpd_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 48c5d482a0d285f25244a63a14bfb306f71da81f
        CONFIG_FILE: proxy.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/lighttpd
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  mongoose:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/cesanta/mongoose
        APP_VERSION: 1f56776050a500b486db00a9142f38849e3f2375
        SERVER_SOURCE: main.c
      context: ./images/mongoose
    x-props:
      role: origin
  netty:
    build:
      args:
        APP_BRANCH: 4.2
        APP_REPO: https://github.com/netty/netty
        APP_VERSION: fe13bf298b91d3ffcc38834c31581dc6c76ef5c6
      context: ./images/netty
    x-props:
      role: origin
  nghttpx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nghttp2/nghttp2
        APP_VERSION: 3b45a19423f6d627828d70e847533c07cc0b0b5e
      context: ./images/nghttpx
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  nghttpx_h2:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nghttp2/nghttp2
        APP_VERSION: 3b45a19423f6d627828d70e847533c07cc0b0b5e
        PARAMS: ;;proto=h2
      context: ./images/nghttpx
    x-props:
      role: h2_transducer
  nginx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 446ce033e5b9e192e228638e826f2a39328d879c
        CONFIG_FILE: nginx.conf
        START_SCRIPT: start.sh
      context: ./images/nginx
    x-props:
      role: origin
  nginx_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 446ce033e5b9e192e228638e826f2a39328d879c
        CONFIG_FILE: nginx-proxy.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/nginx
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  node_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/nodejs/node
        APP_VERSION: 6a46f31144f4dd03e21725ac5f9f7294f0d8b13b
        SCRIPT: app.js
      context: ./images/node_stdlib
    x-props:
      requires-tls: true
      role: origin
  openbsd_httpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/kenballus/obhttpd-linux
        APP_VERSION: 13177feda2e869a13b07221385e850d07b3f16b1
        OPENBSD_SRC_BRANCH: master
        OPENBSD_SRC_REPO: https://github.com/openbsd/src
        OPENBSD_SRC_VERSION: 56696e8786be09c79aaaadb09d99b103c314f835
      context: ./images/openbsd_httpd
    x-props:
      role: origin
  openlitespeed:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: da5f2e7c1dd2c1cdf5e102c76941b2ad429773b9
        CONFIG_FILE: server_config.conf
        START_SCRIPT: start.sh
        VHOST_CONFIG_FILE: server_vhost.conf
      context: ./images/openlitespeed
    x-props:
      role: origin
  openlitespeed_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: da5f2e7c1dd2c1cdf5e102c76941b2ad429773b9
        CONFIG_FILE: proxy_config.conf
        START_SCRIPT: start_proxy.sh
        VHOST_CONFIG_FILE: proxy_vhost.conf
      context: ./images/openlitespeed
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  pound:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/graygnuorg/pound
        APP_VERSION: f896c480892cf8fbc478cc2d356f6e1e795195f6
      context: ./images/pound
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  protocol_http1:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/socketry/protocol-http1
        APP_VERSION: 25b9e48e45d8bb69cd52b6cea9eff6f38885afaa
      context: ./images/protocol_http1
    x-props:
      role: origin
  puma:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/puma/puma
        APP_VERSION: 80fde2b159eeef4ee400fda27215529c903a1eb3
      context: ./images/puma
    x-props:
      role: origin
  squid:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/squid-cache/squid
        APP_VERSION: 73c731779986ab2971d3b15a9cc1a77c22bbacaf
      context: ./images/squid
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  tornado:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/tornadoweb/tornado
        APP_VERSION: eb64d133c1213b150361010608a1d3335ba4cba0
      context: ./images/tornado
    x-props:
      role: origin
  twisted:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/twisted/twisted
        APP_VERSION: aedee3ea72b2c206774fbeae7a54e71939699d54
      context: ./images/twisted
    x-props:
      role: origin
  undertow:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/undertow-io/undertow
        APP_VERSION: 8fd01ae634ae54c2079e8fb4444af804f5e25f29
      context: ./images/undertow
    x-props:
      role: origin
  uvicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/encode/uvicorn
        APP_VERSION: 896661c189a443bca9cb3bc1c371fc1ccb42ab35
      context: ./images/uvicorn
    x-props:
      role: origin
  varnish:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/varnishcache/varnish-cache
        APP_VERSION: 5eb3ed61435ee4de34e28e6633d09a76436961db
      context: ./images/varnish
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  waitress:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/Pylons/waitress
        APP_VERSION: 64c920fc9c85f4d0faf5687f3e86da66d1891975
      context: ./images/waitress
    x-props:
      role: origin
  webrick:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/ruby/webrick
        APP_VERSION: ea124002ee5ff43b6cf846931b2cb898b3f47819
      context: ./images/webrick
    x-props:
      role: origin
  yahns:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        CONFIG_FILE: server.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
        START_SCRIPT: start.sh
      context: ./images/yahns
    x-props:
      role: origin
  yahns_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        CONFIG_FILE: proxy.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
        START_SCRIPT: start_proxy.sh
      context: ./images/yahns
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
